### ISSUE TITLE
Gerar layout e modelo inicial de desenvolvimento

### ISSUE THREAD

**Issue by lucasam** [Agritap/sisintegracao#1]

**Comment by lucasam** [comment]
# Absolutamente responsivo

# Extremamente leve

Nomear os pacotes com.agritap.sisintegracao

**Comment by lucasam** [comment]
Referencias:
http://byrushan.com/projects/ma/v1-2/index.html
http://themeforest.joaogarin.com/ioadmin/#/forms/elements

**Comment by thiagoshs** [comment]
Pessoal encontrei um conteúdo que talvez sejá de grande valia para iniciação do projeto. Esta localizado no site do DEVMEDIA onde fala sobre GXT e GWT, onde é criado uma tela inicial utilizando tais ferramentas. Não sei qual o objetivo se é criar o código do 0. Percebi que é meio caminho andado para o primeiro passo. Estou reformulando o código e realizando alguns testes para verificar se fica legal. 

Se tiverem interesse em dar uma olhada segue abaixo o link 

Site :http://www.devmedia.com.br/desenvolvendo-aplicacoes-java-com-os-frameworks-gwt-e-gxt/26557

**Comment by rafaellagouveia** [comment]
Boa noite!

Comecei a criar o DER do sistema, esta salvo na area de trabalho do computador, pois nao consegui inserir imagem por aqui. 
Acho interessante a gente listar tudo que devera ter no sistema para depois fazer as classes no eclipse.

**Comment by lucasam** [comment]
Adicionei algumas classes de modelo e um layout inicial.
Agora conseguimos criar uma nova tela.
Falta definir como fazer a comunicacao com o servidor e adicionar Gin e Guice.
Modificacoes no branch feature-1

**Comment by thiagoshs** [comment]
Foi adicionado novas inserções no código Side Bar Menu. E assim foi alterado algumas coisas no site.

**Comment by thiagoshs** [comment]
Tutorial de como utilizar comunicação Gin e Guice 

Gin : https://code.google.com/p/google-gin/wiki/GinTutorial#Step_1._Inheriting_the_GIN_module  
Guice: https://github.com/google/guice/wiki/Motivation

**Comment by lucasam** [comment]
Vou abrir um issue separado para questões de segurança e vou dar esse por encerrado
